resources:
- name: flight-school
  type: git
  source:
    uri: https://github.com/elbandito/flight-school
    branch: master
- name: 5m
  type: time
  source: 
    interval: 5m
jobs:
- name: test-app
  plan:
  - get: flight-school
    trigger: true
  - get: 5m
    trigger: true
  - task: tests
    file: flight-school/build.yml
