resources:
- name: flight-school
  type: git
  source:
    uri: https://github.com/elbandito/flight-school
    branch: master
jobs:
- name: test-app
  plan:
  - get: flight-school
    trigger: true
  - task: rspec 
    file: flight-school/build1.yml
